# These are supported funding model platforms

patreon: clintnetwork
custom: ["https://www.paypal.me/clintnetwork", "https://www.blockchain.com/btc/payment_request?address=3AEqgvpiHC2LzPDunf6PBPBLeT98YruKmg"]
