[package]
name = "lucid"
description = "A Fast, Secure and Distributed KV store with a HTTP API."
version = "0.1.2"
authors = ["Clint.Network <me@clint.network>", "rigwild <me@rigwild.dev>"]
edition = "2018"
keywords = ["kv", "distributed", "ledger", "kv-store", "key-value", "rest", "http", "swagger", "websocket"]
repository = "https://github.com/lucid-kv/lucid"
readme = "https://github.com/lucid-kv/lucid/blob/master/README.md"
license = "https://github.com/lucid-kv/lucid/blob/master/LICENSE.md"
documentation = "https://clintnetwork.gitbook.io/lucid/"
categories = ["command-line-interface", "web-programming::http-server", "web-programming::websocket", "authentication", "command-line-utilities", ]
build = "build.rs"

[package.metadata.winres]
ProductName = "Lucid KV"
LegalCopyright = "Copyright © 2019 Lucid - All Rights Reserved"

[badges]
github = { repository = "lucid-kv/lucid", branch = "master" }

[build-dependencies]
winres = "*"

[dependencies]
nickel = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
serde_yaml = "*"
rustflake = "*"
chrono = "*"
include_dir = "*"
jsonwebtoken = "*"
app_dirs = "*"
colored = "*"
yaml-rust = "*"
ring = "*"
uuid = "*"
rand = "*"
warp = "*"
chashmap = "*"
plugin = "*"
#hyper = "*"
#hyper-openssl = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]