[package]
name = "lucid"
description = "A Fast, Secure and Distributed KV store with a HTTP API."
version = "0.1.0"
authors = ["Clint.Network <me@clint.network>"]
edition = "2018"
keywords = ["kv", "distributed", "ledger", "kv-store", "key-value", "distributed key-value"]
repository = "https://github.com/clintnetwork/lucid"
license = "https://github.com/clintnetwork/lucid/blob/master/LICENSE.md"

[badges]
travis-ci = { repository = "clintnetwork/lucid", branch = "master" }

[dependencies]
nickel = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
rustflake = "*"
chrono = "*"
include_dir = "*"
jsonwebtoken = "*"
app_dirs = "*"
colored = "*"
yaml-rust = "*"
rust-crypto = "*"
uuid = "*"
rand = "*"
#reqwest = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]