name: Release
on:
  push:
    branches: [ master, automatic-release ]
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target:
#          - x86_64-unknown-linux-gnu
#          - stable-x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
#          target: stable-x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release

#    - name: Create a Release
#      uses: actions/create-release@v1
#      with:
#        tag_name: "Release 0.1.4 [Auto]"
#        release_name: "Release 0.1.4 [Auto]"
#        body: "Automatic release from Github Action"
#        prerelease: true

