name: RustRelease

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.2
      env:
        GHR_COMPRESS: xz
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
